### ISSUE TITLE
Problems within quiz activity

### ISSUE THREAD

**Issue by adpe** [Syxton/moodle-atto_sketch#2]
Hello @Syxton 

There are problems using this plugin inside a quiz activity. 

- With the base64 inline image, in the preview it show's up the image. But when saving and finishing the attempt afterwards the image isn't visibile. It cuts away the `<img src="....">` html code. Per example in the label activity all is working fine.

- Then I try it out with the Store as image file (atto_sketch | storeinrepo) setting. In the label activity it's working like a charm, but inside the quiz activity when I draw the image and I want to "Insert the Sketch" there's a JS error:
![image](https://user-images.githubusercontent.com/9467708/39355745-4f9a1c62-4a0e-11e8-96fd-04ce7199e09e.png)

This plugin would be very nice, but we want to use it inside quizes.

Kind regards
Adrian

**Comment by Syxton** [comment]
@adpe I've just tested the latest plugin in both Moodle 3.3 and the latest 3.5 release.  They are both working as expected, however I strongly encourage setting the "Store as file" setting to yes.  Are you still seeing this issue?

**Comment by Syxton** [comment]
https://expirebox.com/delete/4d63f3cc17a59357e7008b2e7eafa25a.html  is a quick video of me testing in 3.5

**Comment by adpe** [comment]
Hello @Syxton 

 I can't watch your video (seems to be deleted...), can you upload it again? It's still not working with Moodle 3.5+ (Build: 20180531). What we want it's to input the Sketch image in an "Essay" question. 

Look's like this:
![image](https://user-images.githubusercontent.com/9467708/41283678-85210d8a-6e37-11e8-830a-ded4c14a3823.png)

It throws the above mentioned exception, but only if I want to submit an answer in the HTML editor as Sketch image. 

---

In the question-text and the shown feedback answers it works.

![image](https://user-images.githubusercontent.com/9467708/41283886-15d656dc-6e38-11e8-927d-358921afa467.png)

**Comment by adpe** [comment]
Hello @Syxton 
What's going with this issue?

**Comment by adpe** [comment]
Hello @Syxton 
The problem still exists running Moodle 3.5.5 (Build: 20190311).

**Comment by Syxton** [comment]
@adpe I honestly don't know what is going on.  I'm not seeing the same issues.
![answers questions feedback](https://user-images.githubusercontent.com/989354/57626776-9f38f400-7564-11e9-8f62-9cfce9158daf.jpg)

**Comment by adpe** [comment]
So great. Thanks @Syxton 

Would be great when you improve your instructions, because the `storeinrepo` setting must be set to `Yes` and in the question per example `essay` you must set the `response format` to `HTML-Editor with filepicker` then it works! 

PS: I close this issue now.

Greets
Adrian

**Comment by Syxton** [comment]
@adpe Thank you for letting me know.  I'll update the instructions.
