### ISSUE TITLE
Sketch's don't save?

### ISSUE THREAD

**Issue by ShiftSolutionsAU** [Syxton/moodle-atto_sketch#3]
One of my clients is running Moodle 3.6.1 with the Sketch plugin, and it won't save the sketch, are there dependancies or settings that need to be reviewed?

**Comment by Syxton** [comment]
can you make sure that "Store as image file" setting is enabled.

**Comment by Syxton** [comment]
Sometimes the default way of saving the sketch can get filtered out.  I need to change the default setting I think.

**Comment by ShiftSolutionsAU** [comment]
Thanks for the reply, it seems to have been an issue with a php extension that was missing that Moodle needed, as we went through all the dependencies and fixed them up, and now it works as expected.
