### ISSUE TITLE
Loss or work

### ISSUE THREAD

**Issue by wbuk** [Syxton/moodle-atto_sketch#6]
This extension is fantastic, it allows the student to edit images online. We do testing in schools have had a few testing this plugin. I hope that was OK, Matthew. I did try to message you but was unable.

The overwhelming response was fantastic. There were a number of suggestions, which you may or may not be interested in but I am happy to share them with you as all are really constructive and from those in education. One point, however, I must share is the button in the top left which says "Mini Paint". Users are saying they lose all the work they have done with no warning at all and they can't get it back. We check this and got the same. We suggest an, "Are you sure?" message would solve this, as many keep losing their work by mistake. There are one or to other suggested tweaks from Teacher, Student and Exam boards, contact me if you would like this. Great Plugin, Cheers.

We test and support completely free, it is all to help each other out.

**Comment by Syxton** [comment]
Just commited some code that will move the miniPaint icon/link to the right instead of being left aligned.  This should keep it from being as easilly clicked accedentally.  Closing #5 and #6
