### ISSUE TITLE
Are you planning to upgrade MiniPaint to version 4.10.1 ?

### ISSUE THREAD

**Issue by gilhoo** [Syxton/moodle-atto_sketch#8]
Hi Syxton,
MiniPaint is now on version 4.10.1 and include some nice improvements.
Are you planning to upgrade your plugin to this version ?
Cheers

**Comment by Syxton** [comment]
@gilhoo I have just pushed a commit to upgrade to 4.10.1  Thank you for bringing it to my attention.
